"""empty message

Revision ID: 03ee21c7d022
Revises: bef1b9a1c981
Create Date: 2021-07-24 17:27:08.620278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03ee21c7d022'
down_revision = 'bef1b9a1c981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('relations_ibfk_1', 'relations', type_='foreignkey')
    op.drop_column('relations', 'family_member_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relations', sa.Column('family_member_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('relations_ibfk_1', 'relations', 'person', ['family_member_id'], ['id'])
    # ### end Alembic commands ###
