"""empty message

Revision ID: bef1b9a1c981
Revises: c191c6aad250
Create Date: 2021-07-24 16:44:07.903201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bef1b9a1c981'
down_revision = 'c191c6aad250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relations', sa.Column('relation_type', sa.String(length=120), nullable=True))
    op.drop_column('relations', 'relation_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relations', sa.Column('relation_name', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('relations', 'relation_type')
    # ### end Alembic commands ###
